#!/usr/bin/env python3
"""
Normalise the word bank.

Reads the SQLite data file, removes duplicate (category, word) pairs, sorts the
rows, and rewrites both the SQLite copy used by the frontend and the MySQL
Flyway migration from the same source of truth.

Usage:  python3 scripts/normalize_words.py [--check]
"""
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SQLITE = ROOT / "frontend" / "public" / "V2__Insert_sample_data_SQLite.sql"
MYSQL = ROOT / "src" / "main" / "resources" / "db" / "migration" / "V2__Insert_sample_data.sql"

ROW = re.compile(r"\('([A-Z_]+)',\s*'((?:[^']|'')+)',\s*'((?:[^']|'')*)',\s*'([A-Z]+)'\)")
DIFF_ORDER = {"EASY": 0, "MEDIUM": 1, "HARD": 2}

CATEGORY_ORDER = [
    "LOCATION_PLACE", "GENERAL_ITEM", "FRUIT_VEGETABLE", "DISH", "SWEET",
    "CANDY", "MOVIE", "ANIMAL", "SPORT", "OCCUPATION", "TECHNOLOGY",
    "MUSIC", "COUNTRY",
]


def read_rows(path):
    return ROW.findall(path.read_text(encoding="utf-8", errors="replace"))


# Entries to drop: truncated or duplicated names that slipped into the bank.
REMOVE = {
    ("COUNTRY", "AMERICA"),        # duplicate of UNITED STATES
    ("COUNTRY", "CZECH"),          # truncated
    ("COUNTRY", "UNITED ARAB"),    # truncated
    ("COUNTRY", "DOMINICAN"),      # truncated
}

# Words stored with broken characters.
REPAIR = {"TURR\u00c3\u201cN": "TURRON"}


def dedupe(rows):
    """Keep the first row per (category, word). Earlier rows win."""
    best = {}
    order = []
    for cat, word, hint, diff in rows:
        word = REPAIR.get(word.strip(), word.strip())
        key = (cat, word.upper())
        if key in REMOVE or key in best:
            continue
        best[key] = (cat, word, hint.strip(), diff)
        order.append(key)
    return [best[k] for k in order]


def render(rows, flavour):
    by_cat = defaultdict(list)
    for cat, word, hint, diff in rows:
        by_cat[cat].append((word, hint, diff))

    out = [
        f"-- V2__Insert_sample_data{'_SQLite' if flavour == 'sqlite' else ''}.sql",
        "-- Word bank for the Wheel of Fortune game.",
        "-- Generated by scripts/normalize_words.py - edit the word lists, not this header.",
        f"-- {len(rows)} words across {len(by_cat)} categories, no duplicates.",
        "",
    ]
    for cat in CATEGORY_ORDER + [c for c in by_cat if c not in CATEGORY_ORDER]:
        entries = by_cat.get(cat)
        if not entries:
            continue
        entries.sort(key=lambda e: (DIFF_ORDER.get(e[2], 9), e[0]))
        out.append("-- " + "=" * 58)
        out.append(f"-- {cat} ({len(entries)} words)")
        out.append("-- " + "=" * 58)
        out.append("INSERT INTO words (category, word, hint, difficulty) VALUES")
        lines = [
            f"('{cat}', '{w}', '{h}', '{d}')" for w, h, d in entries
        ]
        out.append(",\n".join(lines) + ";")
        out.append("")
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    rows = read_rows(SQLITE)
    try:
        sys.path.insert(0, str(ROOT / "scripts"))
        from word_additions import ADDITIONS
        extra = [(c, w, h, d) for c, items in ADDITIONS.items() for w, h, d in items]
        print(f"merging {len(extra)} candidate additions")
        rows = rows + extra
    except ImportError:
        print("no scripts/word_additions.py, skipping additions")
    clean = dedupe(rows)
    removed = len(rows) - len(clean)

    counts = Counter(c for c, _, _, _ in clean)
    print(f"read {len(rows)} rows, removed {removed} duplicates, kept {len(clean)}")
    for cat in CATEGORY_ORDER:
        if counts[cat]:
            print(f"  {cat:16s} {counts[cat]}")

    cross = Counter(w for _, w, _, _ in clean)
    repeated = [w for w, n in cross.items() if n > 1]
    if repeated:
        print(f"  ({len(repeated)} words appear in more than one category, which is fine)")

    if check:
        return 1 if removed else 0

    SQLITE.write_text(render(clean, "sqlite"), encoding="utf-8")
    MYSQL.write_text(render(clean, "mysql"), encoding="utf-8")
    print(f"wrote {SQLITE.relative_to(ROOT)} and {MYSQL.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
