# -*- coding: utf-8 -*-
"""
Extra words for the categories the kids actually play.

Hints here are written plainly on purpose - the original word bank uses
cryptic crossword style hints, which are too hard for young players.
Avoid apostrophes in hints: the frontend SQL parser is happier without them.

Merged in by scripts/normalize_words.py. Words already in the bank are ignored,
so it is safe to add freely.
"""

ADDITIONS = {
    "ANIMAL": [
        # Farm and familiar
        ("GOAT", "Farm animal that eats almost anything and says maa", "EASY"),
        ("SHEEP", "Woolly farm animal that gives us jumpers", "EASY"),
        ("LAMB", "Baby sheep", "EASY"),
        ("DONKEY", "Long eared cousin of the horse", "EASY"),
        ("PONY", "Small horse", "EASY"),
        ("CAMEL", "Desert traveller with a hump on its back", "EASY"),
        ("WATER BUFFALO", "Big black farm animal that loves mud and gives milk", "EASY"),
        ("MOUSE", "Tiny grey animal that loves cheese", "EASY"),
        ("RAT", "Bigger cousin of the mouse with a long tail", "EASY"),
        ("HAMSTER", "Tiny pet that stuffs food in its cheeks", "EASY"),
        ("GUINEA PIG", "Round furry pet that squeaks for food", "EASY"),
        ("PUPPY", "Baby dog", "EASY"),
        ("KITTEN", "Baby cat", "EASY"),
        ("CALF", "Baby cow", "EASY"),
        ("FOAL", "Baby horse", "EASY"),
        ("PIGEON", "Grey city bird seen on every rooftop", "EASY"),
        ("MYNA", "Black bird with yellow beak that copies sounds", "EASY"),
        ("BULBUL", "Small singing bird common in gardens", "MEDIUM"),
        ("SPARROW HAWK", "Small hawk that hunts other birds", "MEDIUM"),
        # Big cats and wild mammals
        ("SNOW LEOPARD", "Pale spotted cat of the high mountains", "MEDIUM"),
        ("JAGUAR", "Spotted big cat of the South American jungle", "EASY"),
        ("PUMA", "Big brown wild cat also called a cougar", "MEDIUM"),
        ("LYNX", "Wild cat with tufted ears and a short tail", "MEDIUM"),
        ("BOBCAT", "Small wild cat with a stubby tail", "MEDIUM"),
        ("PANTHER", "Big cat with a coat so dark it looks black", "EASY"),
        ("HYENA", "African animal with a laughing call", "EASY"),
        ("JACKAL", "Wild dog that hunts at night", "MEDIUM"),
        ("COYOTE", "Wild dog of the American desert", "MEDIUM"),
        ("DINGO", "Wild dog of Australia", "MEDIUM"),
        ("FENNEC FOX", "Tiny desert fox with enormous ears", "MEDIUM"),
        ("ARCTIC FOX", "White fox that lives on the snow", "MEDIUM"),
        ("POLAR BEAR", "White bear that hunts on the ice", "EASY"),
        ("GRIZZLY", "Huge brown bear that catches salmon", "EASY"),
        ("RED PANDA", "Small red animal with a ringed tail that loves bamboo", "MEDIUM"),
        ("MONGOOSE", "Quick little animal famous for fighting snakes", "MEDIUM"),
        ("MARKHOR", "Wild goat with twisting horns, the national animal of Pakistan", "MEDIUM"),
        ("IBEX", "Mountain goat with long curved horns", "MEDIUM"),
        ("BLACKBUCK", "Graceful antelope with spiral horns", "HARD"),
        ("ANTELOPE", "Fast plains animal with horns", "EASY"),
        ("GAZELLE", "Slim fast animal that leaps across the plains", "EASY"),
        ("IMPALA", "African antelope that jumps very high", "MEDIUM"),
        ("WILDEBEEST", "African animal that crosses rivers in huge herds", "MEDIUM"),
        ("WARTHOG", "Wild pig with tusks and a bumpy face", "MEDIUM"),
        ("BISON", "Shaggy giant of the American plains", "MEDIUM"),
        ("YAK", "Shaggy mountain cow of the Himalayas", "MEDIUM"),
        ("ELK", "Large deer with huge branching antlers", "MEDIUM"),
        ("REINDEER", "Deer of the far north that pulls a famous sleigh", "EASY"),
        ("OKAPI", "Forest animal with a giraffe neck and zebra legs", "HARD"),
        ("MANDRILL", "Monkey with a bright blue and red face", "MEDIUM"),
        ("BABOON", "Large monkey that walks on all fours", "EASY"),
        ("GIBBON", "Ape with long arms that swings through trees", "MEDIUM"),
        ("MARMOSET", "Tiny monkey small enough to sit in your hand", "MEDIUM"),
        ("LLAMA", "Woolly South American animal that carries loads", "EASY"),
        ("ALPACA", "Soft woolly cousin of the llama", "EASY"),
        ("CAPYBARA", "The largest rodent in the world, loves water", "MEDIUM"),
        ("CHINCHILLA", "Small rodent with the softest fur of all", "MEDIUM"),
        ("PRAIRIE DOG", "Small digger that stands up to whistle a warning", "MEDIUM"),
        ("PANGOLIN", "Animal covered in scales that rolls into a ball", "MEDIUM"),
        ("AARDVARK", "Long nosed animal that digs up ants at night", "MEDIUM"),
        ("WOMBAT", "Chunky Australian digger with a square burrow", "MEDIUM"),
        ("WALLABY", "Small cousin of the kangaroo", "EASY"),
        ("QUOKKA", "Small Australian animal that looks like it is smiling", "MEDIUM"),
        ("TASMANIAN DEVIL", "Small black Australian animal with a very loud screech", "MEDIUM"),
        ("ECHIDNA", "Spiny Australian animal that lays eggs", "MEDIUM"),
        ("MOLE", "Velvety animal that digs tunnels under the lawn", "EASY"),
        ("SEA OTTER", "Sea animal that floats on its back cracking shells", "MEDIUM"),
        ("BAT EARED FOX", "Small fox with giant ears that listens for insects", "HARD"),
        ("INDUS DOLPHIN", "Blind river dolphin of the Indus", "HARD"),
        # Birds
        ("DOVE", "White bird that is a symbol of peace", "EASY"),
        ("MAGPIE", "Black and white bird that likes shiny things", "MEDIUM"),
        ("SWALLOW", "Fast bird with a forked tail that flies south", "EASY"),
        ("NIGHTINGALE", "Small brown bird famous for singing at night", "MEDIUM"),
        ("WREN", "Tiny brown bird with its tail pointing up", "MEDIUM"),
        ("KINGFISHER", "Bright blue bird that dives for fish", "EASY"),
        ("HOOPOE", "Orange bird with a crown of feathers on its head", "MEDIUM"),
        ("LOVEBIRD", "Small colourful parrot that sits in pairs", "EASY"),
        ("BUDGIE", "Small green or blue pet parrot", "EASY"),
        ("COCKATIEL", "Grey pet bird with a yellow crest and orange cheeks", "MEDIUM"),
        ("LORIKEET", "Rainbow coloured parrot that drinks nectar", "MEDIUM"),
        ("KOOKABURRA", "Australian bird with a laughing call", "MEDIUM"),
        ("ROADRUNNER", "Desert bird that runs faster than it flies", "MEDIUM"),
        ("OSPREY", "Fish hunting hawk that plunges feet first", "MEDIUM"),
        ("KESTREL", "Small falcon that hovers before it dives", "MEDIUM"),
        ("CONDOR", "Enormous vulture of the mountains", "MEDIUM"),
        ("IBIS", "Wading bird with a long curved beak", "MEDIUM"),
        ("EGRET", "Tall white bird that stands still in shallow water", "MEDIUM"),
        ("CORMORANT", "Black water bird that dries its wings in the sun", "MEDIUM"),
        ("TERN", "Slim sea bird that hovers then dives", "MEDIUM"),
        ("LOON", "Diving water bird with a haunting call", "HARD"),
        ("SECRETARY BIRD", "Long legged African bird that stamps on snakes", "HARD"),
        # Reptiles and amphibians
        ("SEA TURTLE", "Turtle that swims the ocean and lays eggs on the beach", "EASY"),
        ("TORTOISE", "Slow land reptile that carries its home", "EASY"),
        ("CAIMAN", "Small cousin of the alligator", "MEDIUM"),
        ("GHARIAL", "River crocodile with a very thin snout", "HARD"),
        ("GILA MONSTER", "Chunky orange and black venomous lizard", "HARD"),
        ("HORNED LIZARD", "Spiky desert lizard that squirts blood from its eyes", "HARD"),
        ("ANOLE", "Small green lizard that puffs a pink throat fan", "HARD"),
        ("SIDEWINDER", "Desert snake that moves in loops across the sand", "MEDIUM"),
        ("COPPERHEAD", "Coppery snake that hides in leaves", "MEDIUM"),
        ("ADDER", "Small venomous snake with a zigzag back", "MEDIUM"),
        ("TAIPAN", "One of the most venomous snakes in the world", "HARD"),
        # Sea life
        ("HAMMERHEAD", "Shark with eyes on the ends of a wide flat head", "EASY"),
        ("GREAT WHITE", "The most famous big shark of all", "EASY"),
        ("WHALE SHARK", "The biggest fish in the sea, and it eats tiny plankton", "MEDIUM"),
        ("ANGLERFISH", "Deep sea fish that fishes with a glowing lure", "MEDIUM"),
        ("ELECTRIC EEL", "River fish that gives a powerful shock", "MEDIUM"),
        ("LIONFISH", "Striped fish with fans of venomous spines", "MEDIUM"),
        ("PARROTFISH", "Bright reef fish with a beak that crunches coral", "MEDIUM"),
        ("SARDINE", "Small silver fish that swims in huge shoals", "EASY"),
        ("MACKEREL", "Striped silver sea fish", "MEDIUM"),
        ("STURGEON", "Ancient armoured river fish", "HARD"),
        ("TILAPIA", "Common farmed fish served at dinner", "MEDIUM"),
        ("CUTTLEFISH", "Sea animal that changes colour in a flash", "MEDIUM"),
        ("NAUTILUS", "Sea animal living in a beautiful spiral shell", "HARD"),
        ("HERMIT CRAB", "Crab that borrows an empty shell to live in", "EASY"),
        ("BARNACLE", "Small shelled creature glued to rocks and boats", "MEDIUM"),
        ("KRILL", "Tiny shrimp that whales eat by the tonne", "MEDIUM"),
        # Minibeasts
        ("BUMBLEBEE", "Big fuzzy striped bee", "EASY"),
        ("CATERPILLAR", "Wriggly creature that turns into a butterfly", "EASY"),
        ("EARTHWORM", "Wriggler that makes the soil healthy", "EASY"),
        ("SNAIL SHELL", "The spiral home a snail carries", "MEDIUM"),
        ("LOCUST", "Grasshopper that swarms in millions", "MEDIUM"),
        ("CICADA", "Insect that buzzes loudly on hot days", "MEDIUM"),
        ("DUNG BEETLE", "Beetle that rolls a ball of dung", "MEDIUM"),
        ("STAG BEETLE", "Beetle with jaws like antlers", "MEDIUM"),
        ("YELLOWJACKET", "Striped wasp that crashes picnics", "MEDIUM"),
        ("FIRE ANT", "Tiny ant with a burning sting", "MEDIUM"),
        ("WATER STRIDER", "Insect that walks on the surface of a pond", "HARD"),
        ("GLOW WORM", "Little creature that shines in the dark", "MEDIUM"),
    ],
    "COUNTRY": [
        ("NEW ZEALAND", "Island country of kiwis and sheep near Australia", "EASY"),
        ("NORTH KOREA", "Closed off country north of South Korea", "MEDIUM"),
        ("IVORY COAST", "West African country named after elephant tusks", "MEDIUM"),
        ("CENTRAL AFRICAN", "Country right in the middle of Africa", "HARD"),
        ("SAINT VINCENT", "Small Caribbean island country", "HARD"),
        ("SOUTH KOREA", "Country famous for K pop and Seoul", "EASY"),
        ("UNITED STATES", "Country of fifty states and the Statue of Liberty", "EASY"),
        ("UNITED ARAB EMIRATES", "Gulf country of Dubai and Abu Dhabi", "EASY"),
        ("CZECH REPUBLIC", "European country with Prague as its capital", "MEDIUM"),
        ("DOMINICAN REPUBLIC", "Caribbean country sharing an island with Haiti", "MEDIUM"),
            ],
}

ADDITIONS["FRUIT_VEGETABLE"] = [
    # Fruit the kids will recognise
    ("MANDARIN", "Small orange that peels in seconds", "EASY"),
    ("KINNOW", "Juicy orange grown all over Punjab", "EASY"),
    ("POMELO", "Giant grapefruit with a very thick skin", "MEDIUM"),
    ("BLOOD ORANGE", "Orange that is deep red inside", "MEDIUM"),
    ("SWEET LIME", "Pale green citrus juiced for breakfast", "EASY"),
    ("MOSAMBI", "Sweet green citrus sold by juice carts", "MEDIUM"),
    ("CHIKOO", "Brown fruit that tastes like brown sugar", "MEDIUM"),
    ("JAMUN", "Small purple fruit that stains your tongue", "MEDIUM"),
    ("FALSA", "Tiny purple summer berry sold in cones", "HARD"),
    ("AMLA", "Sour green fruit full of vitamin C", "MEDIUM"),
    ("SHARIFA", "Green bumpy fruit with sweet creamy pulp", "MEDIUM"),
    ("CUSTARD APPLE", "Bumpy green fruit with custard like flesh", "MEDIUM"),
    ("MANGOSTEEN", "Purple fruit with snow white segments inside", "MEDIUM"),
    ("SOURSOP", "Big green spiky fruit with creamy sour flesh", "HARD"),
    ("LOQUAT", "Small orange fruit with big shiny seeds", "MEDIUM"),
    ("PAWPAW", "Soft fruit that tastes like banana and mango", "HARD"),
    ("HUCKLEBERRY", "Small dark wild berry like a blueberry", "MEDIUM"),
    ("LINGONBERRY", "Tart red berry served with Swedish meatballs", "HARD"),
    ("CLOUDBERRY", "Golden northern berry that grows in bogs", "HARD"),
    ("KIWANO", "Spiky orange melon with green jelly inside", "HARD"),
    ("PHYSALIS", "Little orange berry wrapped in a paper lantern", "HARD"),
    ("JUJUBE", "Small crunchy fruit also called a red date", "MEDIUM"),
    ("FEIJOA", "Green egg shaped fruit that smells like perfume", "HARD"),
    ("SAPOTE", "Soft tropical fruit with creamy sweet flesh", "HARD"),
    ("SUGAR APPLE", "Knobbly green fruit that pulls apart in sweet lumps", "MEDIUM"),
    ("WOOD APPLE", "Hard shelled fruit cracked open for its pulp", "HARD"),
    ("GREEN MANGO", "Unripe mango eaten sour with salt", "EASY"),
    ("SEEDLESS GRAPE", "Grape with no pips to spit out", "EASY"),
    ("RED APPLE", "The classic lunchbox fruit", "EASY"),
    ("GREEN APPLE", "Tart crunchy apple", "EASY"),
    ("BANANA BUNCH", "How bananas grow together", "EASY"),
    # Vegetables
    ("ICEBERG LETTUCE", "Crunchy pale lettuce that forms a tight ball", "EASY"),
    ("ROMAINE", "Tall crisp lettuce used in Caesar salad", "MEDIUM"),
    ("BABY SPINACH", "Small tender spinach leaves eaten raw", "EASY"),
    ("MUSTARD GREENS", "Peppery leaves cooked as saag", "MEDIUM"),
    ("FENUGREEK", "Fragrant green leaves called methi", "MEDIUM"),
    ("CORIANDER", "Green herb sprinkled over almost every curry", "EASY"),
    ("MINT LEAVES", "Cool green leaves used in chutney", "EASY"),
    ("CURRY LEAVES", "Shiny leaves crackled in hot oil", "MEDIUM"),
    ("GREEN CHILLI", "Small hot green pepper", "EASY"),
    ("RED CHILLI", "Small hot red pepper", "EASY"),
    ("BELL PEPPER", "Sweet crunchy pepper in red, yellow or green", "EASY"),
    ("BITTER GOURD", "Bumpy green vegetable famous for being bitter", "MEDIUM"),
    ("BOTTLE GOURD", "Long pale green gourd cooked in curry", "MEDIUM"),
    ("RIDGE GOURD", "Ribbed green gourd used in village cooking", "HARD"),
    ("ASH GOURD", "Big pale gourd used for sweets and curry", "HARD"),
    ("IVY GOURD", "Small green vegetable called tinda or tindora", "HARD"),
    ("CLUSTER BEANS", "Slim green beans called guar", "HARD"),
    ("DRUMSTICK", "Long ridged pod cooked in sambar", "MEDIUM"),
    ("MUNG BEAN", "Small green bean that sprouts easily", "MEDIUM"),
    ("ADZUKI BEAN", "Small red bean used in sweet pastes", "HARD"),
    ("BUTTER BEAN", "Big flat creamy white bean", "MEDIUM"),
    ("RUNNER BEAN", "Long flat green bean from the garden", "MEDIUM"),
    ("BEAN SPROUTS", "Crunchy white sprouts added to noodles", "EASY"),
    ("BABY CORN", "Tiny corn cobs eaten whole", "EASY"),
    ("SWEET CORN", "Yellow corn eaten off the cob", "EASY"),
    ("PEARL ONION", "Tiny onion pickled whole", "MEDIUM"),
    ("RED ONION", "Purple skinned onion eaten raw in salad", "EASY"),
    ("SPRING ONION", "Slim onion with long green tops", "EASY"),
    ("ELEPHANT GARLIC", "Giant mild garlic bulb", "HARD"),
    ("NEW POTATO", "Small waxy potato dug up early", "EASY"),
    ("PURPLE CABBAGE", "Cabbage the colour of a plum", "EASY"),
    ("BUTTON MUSHROOM", "Small white mushroom sold in every shop", "EASY"),
    ("KING OYSTER", "Thick stemmed mushroom sliced like scallops", "HARD"),
    ("SUNCHOKE", "Knobbly root also called Jerusalem artichoke", "HARD"),
    ("SALSIFY", "Long thin root that tastes faintly of oyster", "HARD"),
    ("CELTUCE", "Lettuce grown for its thick crunchy stem", "HARD"),
    ("MICROGREENS", "Baby leaves snipped just after sprouting", "MEDIUM"),
    ("PUMPKIN SEEDS", "Flat green seeds roasted for snacking", "EASY"),
    ("CORN ON THE COB", "Whole corn eaten straight off the stick", "EASY"),
    ("SNAKE GOURD", "Very long curling green gourd", "HARD"),
    ("BANANA FLOWER", "Purple flower of the banana plant, cooked as a vegetable", "HARD"),
    ("LOTUS STEM", "Crunchy root with holes running through it", "MEDIUM"),
    ("GREEN PEAS", "Little round green seeds in a pod", "EASY"),
    ("SPROUTED GRAM", "Sprouted chickpeas eaten as a snack", "MEDIUM"),
]

ADDITIONS["SWEET"] = [
    # South Asian sweets the kids know
    ("RAS MALAI", "Soft cheese balls floating in sweet milk", "EASY"),
    ("KAJU KATLI", "Diamond shaped cashew sweet with a silver top", "EASY"),
    ("GAJAR HALWA", "Warm carrot pudding cooked in milk", "EASY"),
    ("SOHAN HALWA", "Chewy Multan sweet packed with nuts", "MEDIUM"),
    ("RABRI", "Thick sweet milk cooked down for hours", "MEDIUM"),
    ("FALOODA", "Tall cold drink with noodles, jelly and ice cream", "EASY"),
    ("SHEER KHURMA", "Eid pudding of milk, dates and vermicelli", "EASY"),
    ("SEVIYAN", "Sweet vermicelli cooked in milk", "EASY"),
    ("ZARDA", "Bright orange sweet rice with nuts", "MEDIUM"),
    ("MALPUA", "Sweet fried pancake soaked in syrup", "MEDIUM"),
    ("SHAHI TUKDA", "Fried bread soaked in sweet creamy milk", "MEDIUM"),
    ("PHIRNI", "Cold rice pudding served in clay bowls", "MEDIUM"),
    ("MISHTI DOI", "Sweet set yoghurt from Bengal", "MEDIUM"),
    ("CHUM CHUM", "Oval Bengali sweet rolled in coconut", "MEDIUM"),
    ("PEDA", "Small round milk sweet", "EASY"),
    ("SANDESH", "Delicate Bengali sweet made from fresh cheese", "MEDIUM"),
    ("MYSORE PAK", "Crumbly sweet of gram flour, ghee and sugar", "MEDIUM"),
    ("IMARTI", "Orange flower shaped syrup sweet", "MEDIUM"),
    ("BALUSHAHI", "Flaky fried sweet like an Indian doughnut", "MEDIUM"),
    ("PATISA", "Layered flaky sweet that melts on the tongue", "MEDIUM"),
    ("KHOYA", "Thickened milk used to make many sweets", "MEDIUM"),
    ("NAN KHATAI", "Crumbly cardamom biscuit from the bakery", "EASY"),
    ("RUSK", "Twice baked bread dunked in tea", "EASY"),
    # Middle Eastern
    ("KNAFEH", "Cheesy pastry in syrup topped with orange threads", "MEDIUM"),
    ("BASBOUSA", "Semolina cake soaked in syrup", "MEDIUM"),
    ("MAAMOUL", "Date filled cookie pressed in a mould", "MEDIUM"),
    ("QATAYEF", "Stuffed folded pancake eaten in Ramadan", "MEDIUM"),
    ("UM ALI", "Warm Egyptian bread pudding with nuts", "HARD"),
    ("LOUKOUMADES", "Little fried dough balls drenched in honey", "HARD"),
    # Everyday favourites
    ("WAFFLE", "Crisp squares cooked in a hot iron", "EASY"),
    ("PANCAKE STACK", "Pile of pancakes with syrup poured over", "EASY"),
    ("CINNAMON ROLL", "Spiral bun with icing on top", "EASY"),
    ("STICKY BUN", "Sweet bun glazed with syrup and nuts", "EASY"),
    ("HONEY BUN", "Soft sweet bun glazed with honey", "EASY"),
    ("APPLE FRITTER", "Chunks of apple fried in sweet batter", "EASY"),
    ("BEAR CLAW", "Fanned pastry shaped like a paw", "MEDIUM"),
    ("JELLY DONUT", "Doughnut that squirts jam when you bite it", "EASY"),
    ("CHOCOLATE MILK", "Milk stirred with chocolate", "EASY"),
    ("HOT CHOCOLATE", "Warm chocolate drink for cold evenings", "EASY"),
    ("CANDY FLOSS", "Spun sugar cloud on a stick", "EASY"),
    ("JELLY", "Wobbly fruit dessert that sets in a mould", "EASY"),
    ("CUSTARD TRIFLE", "Layers of cake, fruit, custard and cream", "EASY"),
    ("BANANA BREAD", "Loaf baked from very ripe bananas", "EASY"),
    ("CHOCOLATE CAKE", "The birthday classic", "EASY"),
    ("VANILLA ICE CREAM", "The plainest and most popular ice cream", "EASY"),
    ("STRAWBERRY SUNDAE", "Ice cream with strawberry sauce and a cherry", "EASY"),
    ("CHOCOLATE CHIP COOKIE", "Cookie studded with chocolate chips", "EASY"),
    ("ICE LOLLY", "Frozen juice on a stick", "EASY"),
    ("KULFI FALOODA", "Kulfi served over sweet noodles", "MEDIUM"),
    # European and East Asian
    ("PASTEL DE NATA", "Portuguese custard tart with a scorched top", "MEDIUM"),
    ("STROOPWAFEL", "Thin waffle with caramel in the middle", "MEDIUM"),
    ("POFFERTJES", "Tiny Dutch pancakes dusted with sugar", "HARD"),
    ("BABKA", "Twisted loaf swirled with chocolate", "MEDIUM"),
    ("RUGELACH", "Little rolled pastry with jam and nuts", "HARD"),
    ("STOLLEN", "Christmas loaf full of fruit and marzipan", "MEDIUM"),
    ("LEBKUCHEN", "Soft German spiced Christmas biscuit", "HARD"),
    ("SPECULOOS", "Crisp spiced biscuit served with coffee", "MEDIUM"),
    ("BRIGADEIRO", "Brazilian chocolate ball rolled in sprinkles", "MEDIUM"),
    ("ALMOND CROISSANT", "Croissant filled with almond cream", "EASY"),
    ("MOCHI ICE CREAM", "Ice cream wrapped in chewy rice dough", "EASY"),
    ("RED BEAN BUN", "Steamed bun filled with sweet red beans", "MEDIUM"),
    ("EGG TART", "Small tart with a wobbly yellow custard", "EASY"),
    ("SESAME BALL", "Fried ball covered in sesame seeds", "MEDIUM"),
    ("PINEAPPLE CAKE", "Little pastry brick filled with pineapple jam", "MEDIUM"),
    ("HONEY CAKE", "Layered cake sweetened with honey", "MEDIUM"),
    ("APPLE STRUDEL", "Thin pastry rolled around spiced apples", "MEDIUM"),
    ("BLACK FOREST CAKE", "Chocolate cake with cherries and cream", "EASY"),
    ("CARAMEL PUDDING", "Wobbly custard with caramel on top", "EASY"),
    ("COTTON CHEESECAKE", "Extra light and jiggly cheesecake", "MEDIUM"),
]
